<?php
/**
 * Pugo - Scan Translations Action
 * 
 * Scans all content directories and generates a translations.yaml file
 * that tracks:
 * - Which languages have content
 * - Which sections exist in each language
 * - Which articles have translations (via translationKey)
 */

namespace Pugo\Actions\Translations;

require_once dirname(__DIR__) . '/ActionResult.php';

use Pugo\Actions\ActionResult;

final readonly class ScanTranslationsAction
{
    public function __construct(
        private string $hugoRoot,
        private array $languages
    ) {}

    public function handle(): ActionResult
    {
        $result = [
            'languages' => [],
            'translations' => [],
        ];
        
        $translationKeys = []; // translationKey => [lang => path]
        
        foreach ($this->languages as $lang => $langConfig) {
            $contentDir = $lang === 'en' 
                ? $this->hugoRoot . '/content'
                : $this->hugoRoot . '/' . ($langConfig['content_dir'] ?? "content.{$lang}");
            
            if (!is_dir($contentDir)) {
                continue;
            }
            
            $langData = [
                'name' => $langConfig['name'],
                'flag' => $langConfig['flag'] ?? $this->getFlag($lang),
                'articles' => 0,
                'sections' => [],
            ];
            
            // Scan sections
            foreach (scandir($contentDir) as $item) {
                if ($item[0] === '.') continue;
                $path = $contentDir . '/' . $item;
                
                if (is_dir($path) && $item !== '_index.md') {
                    $langData['sections'][] = $item;
                }
            }
            
            // Scan all markdown files
            $iterator = new \RecursiveIteratorIterator(
                new \RecursiveDirectoryIterator($contentDir, \RecursiveDirectoryIterator::SKIP_DOTS)
            );
            
            foreach ($iterator as $file) {
                if ($file->isFile() && $file->getExtension() === 'md') {
                    $filename = $file->getBasename();
                    
                    // Skip index files for article count
                    if ($filename !== '_index.md') {
                        $langData['articles']++;
                    }
                    
                    // Extract translationKey
                    $content = file_get_contents($file->getPathname());
                    if (preg_match('/^translationKey:\s*["\']?([^"\'\n]+)["\']?/m', $content, $matches)) {
                        $key = trim($matches[1]);
                        if (!isset($translationKeys[$key])) {
                            $translationKeys[$key] = [];
                        }
                        $translationKeys[$key][$lang] = str_replace($contentDir . '/', '', $file->getPathname());
                    }
                }
            }
            
            sort($langData['sections']);
            $result['languages'][$lang] = $langData;
        }
        
        // Build translations map (only keys with multiple languages)
        foreach ($translationKeys as $key => $langs) {
            if (count($langs) > 1) {
                $result['translations'][$key] = array_keys($langs);
            }
        }
        
        // Generate YAML content
        $yaml = $this->generateYaml($result);
        
        // Write to data file
        $dataFile = $this->hugoRoot . '/data/translations.yaml';
        $dataDir = dirname($dataFile);
        
        if (!is_dir($dataDir)) {
            mkdir($dataDir, 0755, true);
        }
        
        if (file_put_contents($dataFile, $yaml) === false) {
            return ActionResult::failure('Failed to write translations.yaml');
        }
        
        return ActionResult::success(
            message: 'Translations scanned successfully',
            data: $result
        );
    }
    
    private function getFlag(string $lang): string
    {
        return match($lang) {
            'en' => '🇬🇧',
            'fr' => '🇫🇷',
            'es' => '🇪🇸',
            'de' => '🇩🇪',
            'it' => '🇮🇹',
            'nl' => '🇳🇱',
            default => '🌐',
        };
    }
    
    private function generateYaml(array $data): string
    {
        $yaml = "# Translation Status Data\n";
        $yaml .= "# Auto-generated by Pugo - do not edit manually\n";
        $yaml .= "# Last updated: " . date('Y-m-d H:i:s') . "\n\n";
        
        $yaml .= "# Available languages with content\n";
        $yaml .= "languages:\n";
        
        foreach ($data['languages'] as $lang => $info) {
            $yaml .= "  {$lang}:\n";
            $yaml .= "    name: \"{$info['name']}\"\n";
            $yaml .= "    flag: \"{$info['flag']}\"\n";
            $yaml .= "    articles: {$info['articles']}\n";
            $yaml .= "    sections:\n";
            foreach ($info['sections'] as $section) {
                $yaml .= "      - {$section}\n";
            }
        }
        
        $yaml .= "\n# Translation mappings (translationKey -> languages)\n";
        $yaml .= "translations:\n";
        
        if (empty($data['translations'])) {
            $yaml .= "  # No translations found yet\n";
        } else {
            foreach ($data['translations'] as $key => $langs) {
                $yaml .= "  {$key}:\n";
                foreach ($langs as $lang) {
                    $yaml .= "    - {$lang}\n";
                }
            }
        }
        
        return $yaml;
    }
}

